## 데이터 로드

In [26]:
import pandas as pd

# 데이터 처음 5개의 행 표현

df = pd.read_csv("data/bicycle.csv")
df.head(5)

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120

## 결측치 확인

In [2]:
# 결측치 확인. 결측값 True 표현
df.isnull()

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
418,False,False,False,False,False,False,False,False,False,False,False,False
419,False,False,False,False,False,False,False,False,False,False,False,False
420,False,False,False,False,False,False,False,False,False,False,False,False
421,False,False,False,False,False,False,False,False,False,False,False,False
422,False,False,False,False,False,False,False,False,False,False,False,False

In [30]:
# 결측치의 총 개수 출력
df.isnull().sum()

자전거번호       0
대여일시        0
대여소번호       0
대여소명        0
대여거치대      23
반납일시        0
반납대여소번호     0
반납대여소명      0
반납거치대      11
이용시간       11
이용거리       11
나이          0
dtype: int64

In [25]:
# 결측값 False 출력
df.notnull()

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,False,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
418,True,True,True,True,True,True,True,True,True,True,True,True
419,True,True,True,True,True,True,True,True,True,True,True,True
420,True,True,True,True,True,True,True,True,True,True,True,True
421,True,True,True,True,True,True,True,True,True,True,True,True
422,True,True,True,True,True,True,True,True,True,True,True,True

In [39]:
# 데이터의 총 행, 열을 출력
df.shape

(423, 12)

In [41]:
# 총 값과 결측값이 존재하는 열을 출력
df.notnull().sum()

자전거번호      423
대여일시       423
대여소번호      423
대여소명       423
대여거치대      400
반납일시       423
반납대여소번호    423
반납대여소명     423
반납거치대      412
이용시간       412
이용거리       412
나이         423
dtype: int64

## 결측치 행 제거

In [44]:
# NAN 값이 존재하는 행 모두 삭제하여 자기 자신에게 저장
# 확인 시 인덱스 2, 3 번째 줄이 삭제된 것을 확인
df.dropna(inplace = True)
df

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120
5,SPB-18401,2019-11-06 8:52,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:09,3,중랑센터,7.0,11.0,1350.0,30
6,SPB-18350,2019-11-06 8:35,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:10,3,중랑센터,2.0,9.0,1390.0,26
...,...,...,...,...,...,...,...,...,...,...,...,...
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0,28
420,SPB-23012,2019-11-14 19:53,267,삼성화재 사옥 옆,2.0,2019-11-14 20:05,101,(구)합정동 주민센터,2.0,12.0,2350.0,41
421,SPB-13934,2019-11-13 18:00,106,합정역 7번출구 앞,4.0,2019-11-13 18:06,101,(구)합정동 주민센터,2.0,5.0,860.0,58
422,SPB-09287,2019-11-26 8:36,911,은평평화공원(역촌역4번출구),4.0,2019-11-26 9:21,5,상암센터 정비실,6.0,42.0,5800.0,57

In [45]:
# 결측치 삭제 확인
df.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여소명       0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
나이         0
dtype: int64

In [61]:
# 데이터 다시 로드 & 행열 출력
df = pd.read_csv("data/bicycle.csv")
df.shape

(423, 12)

In [48]:
# 데이터 컬럼명 확인
df.columns

Index(['자전거번호', '대여일시', '대여소번호', '대여소명', '대여거치대', '반납일시', '반납대여소번호', '반납대여소명',
       '반납거치대', '이용시간', '이용거리', '나이'],
      dtype='object')

In [50]:
# Nan값이 있는 열을 기준으로 삭제
# 전체 행, 열 확인. print 이용
# 삭제 후 컬럼들 확인
df.dropna(axis=1, inplace=True)
print(df.shape)
df.columns

(423, 8)

Index(['자전거번호', '대여일시', '대여소번호', '대여소명', '반납일시', '반납대여소번호', '반납대여소명', '나이'], dtype='object')

In [51]:
# 특정 행 삭제 & 결측값 개수 확인
df = pd.read_csv("data/bicycle.csv")
df.isnull().sum()

자전거번호       0
대여일시        0
대여소번호       0
대여소명        0
대여거치대      23
반납일시        0
반납대여소번호     0
반납대여소명      0
반납거치대      11
이용시간       11
이용거리       11
나이          0
dtype: int64

In [73]:
# 이용거리의 NaN의 행 삭제 후 확인 결과 인덱스 2번 삭제 확인
df.loc[df["이용거리"].notnull()]

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120
5,SPB-18401,2019-11-06 8:52,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:09,3,중랑센터,7.0,11.0,1350.0,30
...,...,...,...,...,...,...,...,...,...,...,...,...
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0,28
420,SPB-23012,2019-11-14 19:53,267,삼성화재 사옥 옆,2.0,2019-11-14 20:05,101,(구)합정동 주민센터,2.0,12.0,2350.0,41
421,SPB-13934,2019-11-13 18:00,106,합정역 7번출구 앞,4.0,2019-11-13 18:06,101,(구)합정동 주민센터,2.0,5.0,860.0,58
422,SPB-09287,2019-11-26 8:36,911,은평평화공원(역촌역4번출구),4.0,2019-11-26 9:21,5,상암센터 정비실,6.0,42.0,5800.0,57

## 결측 데이터 치환

In [74]:
# 데이터 로드 & 결측치 확인
df = pd.read_csv("data/bicycle.csv")
df.isnull().sum()

자전거번호       0
대여일시        0
대여소번호       0
대여소명        0
대여거치대      23
반납일시        0
반납대여소번호     0
반납대여소명      0
반납거치대      11
이용시간       11
이용거리       11
나이          0
dtype: int64

In [75]:
# 모든 결측치를 0으로 치환, 자기 자신은 변경 X
df.fillna(0)

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,0.0,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,0.0,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120
...,...,...,...,...,...,...,...,...,...,...,...,...
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0,28
420,SPB-23012,2019-11-14 19:53,267,삼성화재 사옥 옆,2.0,2019-11-14 20:05,101,(구)합정동 주민센터,2.0,12.0,2350.0,41
421,SPB-13934,2019-11-13 18:00,106,합정역 7번출구 앞,4.0,2019-11-13 18:06,101,(구)합정동 주민센터,2.0,5.0,860.0,58
422,SPB-09287,2019-11-26 8:36,911,은평평화공원(역촌역4번출구),4.0,2019-11-26 9:21,5,상암센터 정비실,6.0,42.0,5800.0,57

In [76]:
# 모든 결측치를 이전 값으로 치환
df.fillna(method='pad')

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,1420.0,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,7.0,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120
...,...,...,...,...,...,...,...,...,...,...,...,...
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0,28
420,SPB-23012,2019-11-14 19:53,267,삼성화재 사옥 옆,2.0,2019-11-14 20:05,101,(구)합정동 주민센터,2.0,12.0,2350.0,41
421,SPB-13934,2019-11-13 18:00,106,합정역 7번출구 앞,4.0,2019-11-13 18:06,101,(구)합정동 주민센터,2.0,5.0,860.0,58
422,SPB-09287,2019-11-26 8:36,911,은평평화공원(역촌역4번출구),4.0,2019-11-26 9:21,5,상암센터 정비실,6.0,42.0,5800.0,57

In [78]:
# 이용거리 결측치 열을 이용거리 평균으로 치환, 자기 자신 변경
df["이용거리"].fillna(df["이용거리"].mean(), inplace=True)
df

In [80]:
# 모든 결측치를 각 열의 평균으로 처리
df.fillna(df.mean(), inplace=True)

C:\Users\Zeres\AppData\Local\Temp\ipykernel_309152\3824766501.py:2: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(), inplace=True)

In [146]:
# 이용거리를 최빈값으로 치환
df = pd.read_csv("data/bicycle.csv")
data = pd.DataFrame( df[ df["이용거리"].notnull() ]["이용거리"] )
mod = data.value_counts().max()

df["이용거리"].fillna(mod, inplace=True)
df

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리,나이
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0,50
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0,31
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,14.0,32
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0,21
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0,120
...,...,...,...,...,...,...,...,...,...,...,...,...
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0,27
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0,28
420,SPB-23012,2019-11-14 19:53,267,삼성화재 사옥 옆,2.0,2019-11-14 20:05,101,(구)합정동 주민센터,2.0,12.0,2350.0,41
421,SPB-13934,2019-11-13 18:00,106,합정역 7번출구 앞,4.0,2019-11-13 18:06,101,(구)합정동 주민센터,2.0,5.0,860.0,58
422,SPB-09287,2019-11-26 8:36,911,은평평화공원(역촌역4번출구),4.0,2019-11-26 9:21,5,상암센터 정비실,6.0,42.0,5800.0,57

In [124]:
# 결측 개수 확인, 이용거리 결측값이 없어야 한다
df.isnull().sum()

자전거번호      0
대여일시       0
대여소번호      0
대여소명       0
대여거치대      0
반납일시       0
반납대여소번호    0
반납대여소명     0
반납거치대      0
이용시간       0
이용거리       0
나이         0
dtype: int64